version: '3.7'

services: 
    app-server:
        build: 
            context: onlinematchsim
            dockerfile: Dockerfile
        ports: 
            - "8080:8080"
        restart: always
        depends_on: 
            - db 
        environment: 
            SPRING_DATASOURCE_URL : "jdbc:mysql://theprojectdb.cgwbqonltues.us-east-2.rds.amazonaws.com:3306"
            SPRING_DATASOURCE_USERNAME : admin
            SPRING_DATASOURCE_PASSWORD : Admin***
        networks: 
            - backend
            - frontend

    app-client:
        build:
            context: client
            dockerfile: Dockerfile
            args: 
                REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
        ports: 
            - "9090:80"
        restart: always
        depends_on: 
            - app-server
        networks:
            - frontend

    db:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        restart: always
        environment: 
            MYSQL_DATABASE : theprojectdb
            MYSQL_USER : admin
            MYSQL_PASSWORD: Admin***
            MYSQL_ROOT_PASSWORD: Admin***
        volumes:
            - db-data:/var/lib/mysql
        networks: 
            - backend

volumes:
    db-data:

networks: 
    backend:
    frontend: 
